# Uncomment the next line to define a global platform for your project

use_frameworks!
platform :ios, '9.0'

pod 'Firebase/Messaging'

target 'MoralVictory' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'RxSwift',    '~> 4.0'
	pod 'RxCocoa',    '~> 4.0'

  pod 'PureLayout'
  pod 'Hero'

  pod 'Moya'

end
